### PR TITLE
Update build + dependencies

### PR DESCRIPTION
**Pull request by SenseException**

### CODE REVIEW

**Comment by SenseException** [comment]
@greg0ire Can GitHub Actions be introduced in a fork or do I need to have access to the original repository?

**Comment by greg0ire** [comment]
You can introduce GA in a fork, that's how I usually test the migrations to GA, by creating a PR from and to my fork. Another way to be able to see a new GA introduced in a PR on that PR is to have at least one existing GA on the target repository.

**Comment by SenseException** [comment]
I created https://github.com/SenseException/static-website-generator/pull/3 to show the current build states.

**Comment by SenseException** [comment]
@greg0ire ping

**Review by greg0ire — APPROVED** [review]
Sorry for the delay, it looks great!

**Pull request merged**
